"use client";
import { useEffect, useMemo, useState } from "react";
import { Search, Filter } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { formatNpr } from "@/lib/currency";
type Order = { id: string; order_number: string; user_id: string | null; created_at: string; total_amount: number | string; fulfillment_status: string; order_items?: { id: string; quantity: number }[] };
export default function AdminOrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; fetch("/api/v1/orders", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to load orders"); return body.data ?? []; }).then((data) => { if (active) { setOrders(data); setLoading(false); } }).catch((reason) => { if (active) { setError(reason instanceof Error ? reason.message : "Unable to load orders"); setLoading(false); } }); return () => { active = false; }; }, []);
  const visible = useMemo(() => orders.filter((order) => `${order.order_number} ${order.user_id ?? ""}`.toLowerCase().includes(search.toLowerCase())), [orders, search]);
  const statusClass = (status: string) => status === "DELIVERED" ? "bg-green-500/10 text-green-700" : status === "CANCELLED" ? "bg-red-500/10 text-red-700" : status === "SHIPPED" ? "bg-purple-500/10 text-purple-700" : "bg-yellow-500/10 text-yellow-700";
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold font-serif mb-1">Orders</h1><p className="text-muted-foreground text-sm">Live orders from Supabase.</p></div>{error && <p className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">{error}</p>}<div className="bg-card rounded-lg border border-border shadow-sm overflow-hidden"><div className="p-4 border-b border-border flex items-center justify-between bg-muted/20"><div className="relative w-full sm:w-72"><Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" /><Input placeholder="Search orders..." className="pl-9 bg-background" value={search} onChange={(event) => setSearch(event.target.value)} /></div><Button variant="outline" className="hidden sm:flex gap-2 bg-background"><Filter className="h-4 w-4" /> Filter</Button></div><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="text-xs text-muted-foreground uppercase bg-muted/50"><tr><th className="px-6 py-4">Order ID</th><th className="px-6 py-4">Customer ID</th><th className="px-6 py-4">Date</th><th className="px-6 py-4">Items</th><th className="px-6 py-4">Total</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y divide-border">{loading ? <tr><td colSpan={6} className="px-6 py-12 text-center text-muted-foreground">Loading orders...</td></tr> : visible.map((order) => <tr key={order.id}><td className="px-6 py-4 font-medium">{order.order_number}</td><td className="px-6 py-4 text-xs text-muted-foreground">{order.user_id ?? "Guest"}</td><td className="px-6 py-4 text-muted-foreground">{new Date(order.created_at).toLocaleDateString()}</td><td className="px-6 py-4">{order.order_items?.reduce((sum, item) => sum + item.quantity, 0) ?? 0} books</td><td className="px-6 py-4 font-medium">{formatNpr(order.total_amount)}</td><td className="px-6 py-4"><Badge variant="outline" className={`border-transparent ${statusClass(order.fulfillment_status)}`}>{order.fulfillment_status}</Badge></td></tr>)}</tbody></table></div>{!loading && !visible.length && <p className="p-10 text-center text-muted-foreground">No orders found.</p>}</div></div>;
}
