-- Supporting schema only. The existing public.books table is intentionally never altered.
-- Verify public.books.id type and existing RLS before applying this migration.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = timezone('utc', now()); return new; end; $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, full_name text, avatar_url text, role text not null default 'CUSTOMER' check (role in ('CUSTOMER','ADMIN')), status text not null default 'ACTIVE' check (status in ('ACTIVE','DISABLED')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.categories (id uuid primary key default gen_random_uuid(), name varchar(120) not null unique, slug varchar(140) not null unique, description text, status text not null default 'ACTIVE' check (status in ('ACTIVE','ARCHIVED')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.book_gallery (id uuid primary key default gen_random_uuid(), book_id uuid not null references public.books(id) on delete cascade, image_url text not null, display_order integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.reviews (id uuid primary key default gen_random_uuid(), book_id uuid not null references public.books(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, rating integer not null check (rating between 1 and 5), title varchar(200), content text not null, helpful_count integer not null default 0 check (helpful_count >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(book_id,user_id));
create table if not exists public.cart_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, book_id uuid not null references public.books(id) on delete cascade, quantity integer not null check (quantity > 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id,book_id));
create table if not exists public.wishlist_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, book_id uuid not null references public.books(id) on delete cascade, created_at timestamptz not null default now(), unique(user_id,book_id));
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), order_number varchar(40) not null unique, user_id uuid references auth.users(id), subtotal numeric(10,2) not null check (subtotal >= 0), shipping_fee numeric(10,2) not null default 0 check (shipping_fee >= 0), total_amount numeric(10,2) not null check (total_amount >= 0), payment_status text not null default 'PENDING' check (payment_status in ('PENDING','PAID','FAILED','REFUNDED')), fulfillment_status text not null default 'PENDING' check (fulfillment_status in ('PENDING','PROCESSING','SHIPPED','DELIVERED','CANCELLED')), shipping_address jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, book_id uuid references public.books(id), quantity integer not null check (quantity > 0), unit_price numeric(10,2) not null check (unit_price >= 0), created_at timestamptz not null default now());
create table if not exists public.order_events (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, event_type varchar(80) not null, description text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), created_by uuid references auth.users(id));

create index if not exists book_gallery_book_id_idx on public.book_gallery(book_id); create index if not exists reviews_book_id_idx on public.reviews(book_id); create index if not exists cart_items_user_id_idx on public.cart_items(user_id); create index if not exists orders_user_id_idx on public.orders(user_id); create index if not exists order_events_order_id_idx on public.order_events(order_id);
do $$ declare t text; begin foreach t in array array['profiles','categories','reviews','cart_items','orders'] loop execute format('drop trigger if exists %I_updated_at on public.%I', t, t); execute format('create trigger %I_updated_at before update on public.%I for each row execute function public.set_updated_at()', t, t); end loop; end $$;

alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.book_gallery enable row level security; alter table public.reviews enable row level security; alter table public.cart_items enable row level security; alter table public.wishlist_items enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.order_events enable row level security;
create or replace function public.is_admin() returns boolean language sql security definer set search_path = public as $$ select exists(select 1 from public.profiles where id = auth.uid() and role='ADMIN' and status='ACTIVE'); $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,new.raw_user_meta_data->>'full_name') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create policy profiles_read on public.profiles for select using (id=auth.uid() or public.is_admin()); create policy profiles_insert on public.profiles for insert with check (id=auth.uid()); create policy profiles_update on public.profiles for update using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());
revoke update on public.profiles from authenticated; grant update(email,full_name,avatar_url,updated_at) on public.profiles to authenticated;
create policy categories_public on public.categories for select using (status='ACTIVE' or public.is_admin()); create policy categories_admin on public.categories for all using (public.is_admin()) with check (public.is_admin());
create policy gallery_public on public.book_gallery for select using (true); create policy gallery_admin on public.book_gallery for all using (public.is_admin()) with check (public.is_admin());
create policy reviews_public on public.reviews for select using (true); create policy reviews_owner on public.reviews for insert with check (user_id=auth.uid()); create policy reviews_manage on public.reviews for update using (user_id=auth.uid() or public.is_admin()) with check (user_id=auth.uid() or public.is_admin()); create policy reviews_delete on public.reviews for delete using (user_id=auth.uid() or public.is_admin());
create policy cart_owner on public.cart_items for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy wishlist_owner on public.wishlist_items for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy orders_owner on public.orders for select using (user_id=auth.uid() or public.is_admin()); create policy orders_admin on public.orders for all using (public.is_admin()) with check (public.is_admin()); create policy order_items_owner on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_admin()))); create policy events_admin on public.order_events for all using (public.is_admin()) with check (public.is_admin());
